const addressActionTypes = {
  FETCH_CUSTOMER_ADDRESSES_START: "FETCH_CUSTOMER_ADDRESSES_START",
  FETCH_CUSTOMER_ADDRESSES_SUCCESS: "FETCH_CUSTOMER_ADDRESSES_SUCCESS",
  FETCH_CUSTOMER_ADDRESSES_FAILURE: "FETCH_CUSTOMER_ADDRESSES_FAILURE",
  FETCH_CUSTOMER_ADDRESS_START: "FETCH_CUSTOMER_ADDRESS_START",
  FETCH_CUSTOMER_ADDRESS_SUCCESS: "FETCH_CUSTOMER_ADDRESS_SUCCESS",
  FETCH_CUSTOMER_ADDRESS_FAILURE: "FETCH_CUSTOMER_ADDRESS_FAILURE",
  ADD_CUSTOMER_ADDRESS_START: "ADD_CUSTOMER_ADDRESS_START",
  ADD_CUSTOMER_ADDRESS_FAILURE: "ADD_CUSTOMER_ADDRESS_FAILURE",
  UPDATE_CUSTOMER_ADDRESS_START: "UPDATE_CUSTOMER_ADDRESS_START",
  UPDATE_CUSTOMER_ADDRESS_FAILURE: "UPDATE_CUSTOMER_ADDRESS_FAILURE",
  DELETE_CUSTOMER_ADDRESS_START: "DELETE_CUSTOMER_ADDRESS_START",
  DELETE_CUSTOMER_ADDRESS_FAILURE: "DELETE_CUSTOMER_ADDRESS_FAILURE"
};

export default addressActionTypes;
