const CustomerActionTypes = {
  EMAIL_SIGN_IN_START: "EMAIL_SIGN_IN_START",
  CUSTOMER_REGISTER_START: "CUSTOMER_REGISTER_START",
  CUSTOMER_REGISTER_SUCCESS: "CUSTOMER_REGISTER_SUCCESS",
  CUSTOMER_REGISTER_FAILURE: "CUSTOMER_REGISTER_FAILURE",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_IN_FAILURE: "SIGN_IN_FAILURE",
  SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
  SIGN_OUT_FAILURE: "SIGN_OUT_FAILURE",
  GOOGLE_SIGN_IN_START: "GOOGLE_SIGN_IN_START",
  CHECK_CUSTOMER_IS_LOGGED_IN: "CHECK_CUSTOMER_IS_LOGGED_IN",
  SIGN_OUT_START: "SIGN_OUT_START"
};

export default CustomerActionTypes;
