const cartActionTypes = {
  ADD_PRODUCT_TO_CART_START: "ADD_PRODUCT_TO_CART_START",
  ADD_PRODUCT_TO_CART_SUCCESS: "ADD_PRODUCT_TO_CART_SUCCESS",
  ADD_PRODUCT_TO_CART_FAILURE: "ADD_PRODUCT_TO_CART_FAILURE",
  REMOVE_PRODUCT_FROM_CART: "REMOVE_PRODUCT_FROM_CART"
};

export default cartActionTypes;
