const cartActionTypes = {
  ADD_PRODUCT_TO_CART_START: "ADD_PRODUCT_TO_CART_START",
  ADD_PRODUCT_TO_CART_SUCCESS: "ADD_PRODUCT_TO_CART_SUCCESS",
  ADD_PRODUCT_TO_CART_FAILURE: "ADD_PRODUCT_TO_CART_FAILURE",
  ADD_CART_PRODUCT_QUANTITY: "ADD_CART_PRODUCT_QUANTITY",
  REMOVE_PRODUCT_FROM_CART: "REMOVE_PRODUCT_FROM_CART",
  TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
  SET_DELIVERY_PRICE: "SET_DELIVERY_PRICE",
  CLEAR_CART: "CLEAR_CART"
};

export default cartActionTypes;
