const orderActionTypes = {
  PROCESS_PAYMENT_START: "PROCESS_PAYMENT_START",
  PROCESS_PAYMENT_SUCCESS: "PROCESS_PAYMENT_SUCCESS",
  PROCESS_PAYMENT_FAILURE: "PROCESS_PAYMENT_FAILURE"
};

export default orderActionTypes;
