const orderActionTypes = {
  PROCESS_PAYMENT_START: "PROCESS_PAYMENT_START",
  PROCESS_PAYMENT_SUCCESS: "PROCESS_PAYMENT_SUCCESS",
  PROCESS_PAYMENT_FAILURE: "PROCESS_PAYMENT_FAILURE",
  CLEAR_PURCHASED_ORDER: "CLEAR_PURCHASED_ORDER"
};

export default orderActionTypes;
