const orderActionTypes = {
  PROCESS_PAYMENT_START: "PROCESS_PAYMENT_START",
  PROCESS_PAYMENT_SUCCESS: "PROCESS_PAYMENT_SUCCESS",
  PROCESS_PAYMENT_FAILURE: "PROCESS_PAYMENT_FAILURE",
  CLEAR_PURCHASED_ORDER: "CLEAR_PURCHASED_ORDER",
  FETCH_ORDERS_START: "FETCH_ORDERS_START",
  FETCH_ORDERS_SUCCESS: "FETCH_ORDERS_SUCCESS",
  FETCH_ORDERS_FAILURE: "FETCH_ORDERS_FAILURE",
  FETCH_ORDER_START: "FETCH_ORDER_START",
  FETCH_ORDER_SUCCESS: "FETCH_ORDER_SUCCESS",
  FETCH_ORDER_FAILURE: "FETCH_ORDER_FAILURE"
};

export default orderActionTypes;
