const AdminActionTypes = {
  ADMIN_EMAIL_SIGN_IN_START: "ADMIN_EMAIL_SIGN_IN_START",
  ADMIN_SIGN_IN_SUCCESS: "ADMIN_SIGN_IN_SUCCESS",
  ADMIN_SIGN_IN_FAILURE: "ADMIN_SIGN_IN_FAILURE",
  ADMIN_SIGN_OUT_SUCCESS: "ADMIN_SIGN_OUT_SUCCESS",
  ADMIN_SIGN_OUT_FAILURE: "ADMIN_SIGN_OUT_FAILURE",
  CHECK_ADMIN_SIGNED_IN: "CHECK_ADMIN_SIGNED_IN",
  ADMIN_SIGN_OUT_START: "ADMIN_SIGN_OUT_START",
  ADMIN_REGISTER_START: "ADMIN_REGISTER_START",
  ADMIN_REGISTER_SUCCESS: "ADMIN_REGISTER_SUCCESS",
  ADMIN_REGISTER_FAILURE: "ADMIN_REGISTER_FAILURE"
};

export default AdminActionTypes;
