const ProductActionTypes = {
  FETCH_PRODUCTS_START: "FETCH_PRODUCTS_START",
  FETCH_PRODUCTS_SUCCESS: "FETCH_PRODUCTS_SUCCESS",
  FETCH_PRODUCTS_FAILURE: "FETCH_ADMIN_PRODUCTS_FAILURE",
  FETCH_PRODUCT_START: "FETCH_PRODUCT_START",
  FETCH_PRODUCTS_BY_CATEGORY_START: "FETCH_PRODUCTS_BY_CATEGORY_START",
  FETCH_PRODUCTS_BY_CATEGORY_SUCCESS: "FETCH_PRODUCTS_BY_CATEGORY_SUCCESS",
  FETCH_PRODUCTS_BY_CATEGORY_FAILURE: "FETCH_PRODUCTS_BY_CATEGORY_FAILURE",
  FETCH_PRODUCT_SUCCESS: "FETCH_PRODUCT_SUCCESS",
  FETCH_PRODUCT_FAILURE: "FETCH_ADMIN_PRODUCT_FAILURE",
  ADD_ADMIN_PRODUCT_START: "ADD_ADMIN_PRODUCT_START",
  ADD_ADMIN_PRODUCT_FAILURE: "ADD_ADMIN_PRODUCT_FAILURE",
  ADMIN_DELETE_PRODUCT_START: "ADMIN_DELETE_PRODUCT_START",
  ADMIN_DELETE_PRODUCT_FAILURE: "ADMIN_DELETE_PRODUCT_FAILURE",
  ADMIN_UPDATE_PRODUCT_START: "ADMIN_UPDATE_PRODUCT_START",
  ADMIN_UPDATE_PRODUCT_FAILURE: "ADMIN_UPDATE_PRODUCT_FAILURE"
};

export default ProductActionTypes;
